name: ESX + OX Server
version: 1.0.0
author: Ceravolo
description: Base server con OX Core, ox_inventory, e addon ESX da ESX-Legacy-Addons.

tasks:
  - action: connect_database

  # OX Framework
  - action: download_github
    src: overextended/ox_core
    ref: main
    dest: ./resources/[ox]/ox_core

  - action: download_github
    src: overextended/ox_lib
    ref: main
    dest: ./resources/[ox]/ox_lib

  - action: download_github
    src: overextended/ox_inventory
    ref: main
    dest: ./resources/[ox]/ox_inventory

  - action: download_github
    src: overextended/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  # ESX-Legacy Addons (intero repository)
  - action: download_github
    src: esx-framework/ESX-Legacy-Addons
    ref: main
    dest: ./resources/[esx_addons]

  # Query Database da sottocartelle
  - action: query_database
    file: ./resources/[esx_addons]/esx_addonaccount/esx_addonaccount.sql

  - action: query_database
    file: ./resources/[esx_addons]/esx_billing/esx_billing.sql

  - action: query_database
    file: ./resources/[esx_addons]/esx_society/esx_society.sql

  # Attiva le risorse
  - action: write_file
    file: ./server.cfg
    append: true
    data: |
      ensure ox_lib
      ensure ox_core
      ensure ox_inventory
      ensure ox_target

      ensure [esx_addons]/esx_addonaccount
      ensure [esx_addons]/esx_billing
      ensure [esx_addons]/esx_society
      ensure [esx_addons]/esx_policejob
      ensure [esx_addons]/esx_ambulancejob
